### ISSUE TITLE
Base flow profile for Eady?

### ISSUE THREAD

**Issue by navidcy** [OceanBioME/OceanBioME.jl#108]
Why do we subtract `- p.Lz/2` here?

https://github.com/OceanBioME/OceanBioME.jl/blob/03ace76aabc7d1cbc8340423ddb098c39197282d/examples/eady.jl#L33-L34

Is this an attempt to make it symmetric about the center of the z-domain?

**Comment by glwagner** [comment]
I guess it makes the vertical average 0, perhaps that is desirable

**Comment by navidcy** [comment]
But it doesn't! It should be `+ p.Lz/2` since z-domain is `[-grid.Lz, 0]`, right?

**Comment by glwagner** [comment]
Ah

**Comment by navidcy** [comment]
I guess at the end of the day it doesn't really matter -- it's just a gallilean transformation by constant velocity.
But to minimize questions by readers I changed it in #124.
