### ISSUE TITLE
Ratiation or Radiation

### ISSUE THREAD

**Issue by navidcy** [OceanBioME/OceanBioME.jl#116]
I saw this a lot in the code and I thought it was a typo... but then I see it even here:

https://github.com/OceanBioME/OceanBioME.jl/blob/2815e3633cc16a2a7bb732bdd85b1b4768330326/src/Light/2band.jl#L1

Is it a typo or a term I am not aware of?

If it's actually legit then note I may have replaced some with `radiation` in the docs...

**Comment by jagoosw** [comment]
This is a typo

**Comment by jagoosw** [comment]
Ah dear its even in the public API

**Comment by navidcy** [comment]
Keep calm and bump a minor release.
