### ISSUE TITLE
Light attenuation model does not work on lat/lon grids

### ISSUE THREAD

**Issue by jagoosw** [OceanBioME/OceanBioME.jl#119]
Light attenuation model does not work on lat/lon grids because `xnode` is defined differently for each. I imagine this may have been fixed recently in Oceananigans so will just be a case of updating the use of the `xnode` function.

**Comment by navidcy** [comment]
I'm not sure exactly what you mean with "defined differently".

Actually it _used_ to be the case that `xnode(s)` would return different coordinates depending (meters or degrees) depending on the grid and we remedy that. This change was introduced in v0.81 by https://github.com/CliMA/Oceananigans.jl/pull/2979?

```
nodes(grid, ℓx, ℓy, ℓz)
```

Will return the grid's native coordinates so you can always do `nodes(grid, ℓx, ℓy, ℓz)[1]` to get the zonal coordinate on any grid.
