### ISSUE TITLE
Why does `CenterField` contain no data for `BoxModelGrid`?

### ISSUE THREAD

**Issue by glwagner** [OceanBioME/OceanBioME.jl#165]
I noticed that `CenterField` is defined as `nothing` on ` BoxModelGrid`:

https://github.com/OceanBioME/OceanBioME.jl/blob/4b7b1202c99107d7475a84feb7bd5b084b229f4d/src/BoxModel/boxmodel.jl#L190

But if I understand this correctly, a box model grid is effectively 0-dimensional. That means that any field would actually have 1 point (not 0 points). Otherwise, what is the prognostic state of a `BoxModel`?

I'm asking because I think the concept of a 0D grid could be possibly useful in Oceananigans (but right now we use a triply-`Flat` grid for the same purpose when we need it).

**Comment by jagoosw** [comment]
This is a good question, I think at the time of writing it was just a workaround to allow models to be constructed. I'll have a look at how its used.

Tbh all of the box model code could do with some rethinking to be better aligned with the rest of the code. No one's used it much so it's not had a lot of testing or thought.

**Comment by glwagner** [comment]
How is the prognostic state of a BoxModel stored?

**Comment by jagoosw** [comment]
Just as a Tuple of Floats (vs a tuple of fields in Oceananigans)

**Comment by glwagner** [comment]
Ah, I realize that you are not using an Oceananigans model in this case. So the question is really why / where `CenterField` gets called at all.

**Comment by navidcy** [comment]
@jagoosw this was resolved with #164, right?

**Comment by jagoosw** [comment]
yeah, sorry should have said!
