### ISSUE TITLE
Update gas transfer coefficients

### ISSUE THREAD

**Issue by vtamsitt** [OceanBioME/OceanBioME.jl#168]
I'm interested in implementing updated gas transfer velocity (k) parameterisations (at the very least, Wanninkhof 1992 is outdated and could be replaced by [Wanninkhof 2014](https://aslopubs.onlinelibrary.wiley.com/doi/abs/10.4319/lom.2014.12.351)). It would be great to add other gas transfer velocities e.g. Ho et al. 2006, as is mentioned in the code comments. I'm guessing the best way to implement this would be to add all of these parameterisations (and more?) and include a kwarg when calling GasExchange? 
https://github.com/OceanBioME/OceanBioME.jl/blob/0b45a16ee2017af6ac3d8cebbbb613760983d6ae/src/Boundaries/gasexchange.jl#L127

**Comment by johnryantaylor** [comment]
Hi @vtamsitt, thanks! That would be great and what you suggest seems like a good approach

**Comment by vtamsitt** [comment]
Great, I'll work on this when I get a chance.

**Comment by glwagner** [comment]
It could make sense to add a property called `transfer_velocity` here:

https://github.com/OceanBioME/OceanBioME.jl/blob/0b45a16ee2017af6ac3d8cebbbb613760983d6ae/src/Boundaries/gasexchange.jl#L142

then it'll be easy to add new models (for developers) or to switch between models (for users)

**Comment by jagoosw** [comment]
Closed by #186
