### ISSUE TITLE
Hard-coded `Float64` values

### ISSUE THREAD

**Issue by glwagner** [OceanBioME/OceanBioME.jl#218]
I suspect there will be people cropping up (👀  @ali-ramadhan) want to use `Float32`. This will thwart them:

https://github.com/OceanBioME/OceanBioME.jl/blob/3c287d625aa7135c8297fa36b94347979344c235/src/Models/AdvectedPopulations/NPZD.jl#L320

All that's needed is

```julia
@inline redfield(::Union{Val{:P}, Val{:Z}, Val{:D}}, bgc::NPZD{FT}) where FT = convert(FT, 6.56)
```

The key is to never write decimals in source code without `convert`.

**Comment by johnryantaylor** [comment]
Thanks for the tip @glwagner!

**Comment by ali-ramadhan** [comment]
Not sure if nitpicking but would

```julia
@inline redfield(::Union{Val{:P}, Val{:Z}, Val{:D}}, bgc::NPZD{FT}) where FT = FT(6.56)
```

be better than

```julia
@inline redfield(::Union{Val{:P}, Val{:Z}, Val{:D}}, bgc::NPZD{FT}) where FT = convert(FT, 6.56)
```

to avoid extra layer(s) of method inference during compilation?

**Comment by glwagner** [comment]
Well, I thought they were the same!

In Oceananigans source code we have been trying to migrate to `convert(FT, x)` simply because we felt it was more semantically obvious than merely `FT(x)` which is easier to forget exactly what it does first thing in the morning or at the end of a long day (well, it converts `x` to `FT` of course).

**Comment by ali-ramadhan** [comment]
That makes sense! For floats it's a super simple method inference. Maybe for more complex types there's more extra inference. But agree it's good to be more semantically obvious!
