### ISSUE TITLE
`scale_negative_tracers` fails on GPU

### ISSUE THREAD

**Issue by jagoosw** [OceanBioME/OceanBioME.jl#70]
Everything else seems to work okay on GPU now except the utilities for stopping tracers going negative. When a GPU node becomes available I'll try and get this working.

**Comment by iuryt** [comment]
Could fix this? I did something similar and it worked in GPU, maybe it helps.

**Comment by iuryt** [comment]
This might be not applicable to your case as I had a way simpler model, but I am posting here in case it helps. I have used this for V100 and A100 GPUs.


```julia
# zeroing negative values
@inline function zeroing(sim)
    @unroll for tracer in [:P, :N, :Nr]
        parent(sim.model.tracers[tracer]) .= max.(0, parent(sim.model.tracers[tracer]))
    end
end
simulation.callbacks[:zeroing] = Callback(zeroing)
```

https://github.com/iuryt/NorthAtlanticBloom/blob/4d0d20cd9549c8eb78ae8b827518ee2756ae6807/src/01-model/02-submesoscale.jl#L223-L229

**Comment by jagoosw** [comment]
I've got this sorted now, thank you for offering though!

Mine didn't origionally work because kernel functions can't take symbols so I chaneged todo what Oceananigans tendencies do and used indices instead. Tests are failing still but its a depdnecy version issue rather than anything else. 

Thanks though!

**Comment by iuryt** [comment]
Nice! Yeah, I also had a problem with unicode characters while using GPU. 
Not sure if there is an open issue for this on Oceananigans, but maybe this is something we could add there.

**Comment by jagoosw** [comment]
I think its more of a general issue with KernelAbstractions not being able to compile something.
