### ISSUE TITLE
Hiding output for `run!(simulation)` in Docs (Warnings)

### ISSUE THREAD

**Issue by iuryt** [OceanBioME/OceanBioME.jl#80]
Hi,

Very cool that this package is being released! Great work!
I am definitely planning to use this package and maybe even contribute at some point.

I was checking the documentation and noticed a lot of warnings in the pattern of
`Warning: type parameters for ... do not match type NamedTuple in workspace`

e.g.:
https://oceanbiome.github.io/OceanBioME.jl/dev/generated/kelp/

I am not sure if this is because of the way the data is being saved or if we should just ignore it, but I was wondering if it would be a good idea to hide those warnings for the examples on docs.

**Comment by jagoosw** [comment]
Thanks!

Oh yes, thank you for noting this. I'm not sure what that warning is about since I don't get it when I run the example locally so I will try and hide it for the docs.

The docs are definitly a work in progress still so I'm sure there's other issues there so the help is much appreciated!

**Comment by iuryt** [comment]
Once in a while, I take a look at the things you are doing to learn and maybe find something I could help.
I will let you know if I find something else.

**Comment by johnryantaylor** [comment]
I think this link might describe a workaround for this problem: https://github.com/JuliaIO/JLD2.jl/issues/328

**Comment by navidcy** [comment]
Is this resolved?

**Comment by jagoosw** [comment]
Kind of. The problem that produced all the output is still there but is removed before the docs are compiled.
