### ISSUE TITLE
kelp example

### ISSUE THREAD

**Issue by johnryantaylor** [OceanBioME/OceanBioME.jl#81]
For some reason, the kelp growth model doesn't seem to be doing anything in this example.  The area, carbon, and nitrogen are constant on the kelp particles throughout the simulation.

**Comment by jagoosw** [comment]
That's weird, I'll look into it.

I wonder if it's related to #80 since that's a warning about the output writer too

**Comment by jagoosw** [comment]
I've just realised the particles never get put into the model:
https://github.com/OceanBioME/OceanBioME.jl/blob/e127bec0bc4828a5ec686e03ce7e52106f8d680b/examples/kelp.jl#L55-L59
Should read:
```julia
biogeochemistry = LOBSTER(; grid,
                            surface_phytosynthetically_active_radiation = PAR⁰,
                            carbonates = true,
                            variable_redfield = true,
                            particles)
```
