### ISSUE TITLE
PAR units

### ISSUE THREAD

**Issue by jagoosw** [OceanBioME/OceanBioME.jl#83]
Hi all,

I think we need to clarify the units for PAR. LOBSTER (and other BGC models) seem to use W/m $^2$ while e.g. the kelp model use einsteim/m $^2$ /day.

Since PAR is defined as an integral between 400 and 700nm (by [MODIS](https://oceancolor.gsfc.nasa.gov/docs/technical/atbd_mod20.pdf) at least) then we can take the very rough approximaiton at the central wavelength for putting it into the BGC models, but I don't know if this is the best solution.

At the moment we're implicitly assuming W/m $^2$ and converting for the kelp model:

https://github.com/OceanBioME/OceanBioME.jl/blob/70ff47f3326cbe668eb92fdf0f6222a1ae96cdd2/src/Models/Individuals/SLatissima.jl#L536

(This is, as far as I can tell, also being done wrong). I'm not exactly sure when this got added in but we need to a) agree on units for the defaults, and b) agree how to convert for the different models.

I think the above should read:
```julia
...* day / (3.99e-10 * (299792458 / 550e-9))
```
(the second factor is ~545e12 so we've lost a factor somewhere in the past)

**Comment by syou83syou83** [comment]
Hi Jago,
I am not sure if I understand this point here. Isn't 299792458 / 550e-9 equivalent to 545e12?

**Comment by jagoosw** [comment]
Oh yeah, sorry my mistake! 

I do think we should agree a standard unit for light. Maybe PAR in Einsteins and light intensity (or something else) in W/m^2.

**Comment by jagoosw** [comment]
We do watts/m^2
