### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by navidcy** [OceanBioME/OceanBioME.jl#90]
The repository is very large. Does it include large output files? If even something was committed in main, even if then deleted it still exists in the repo's history. Or it could be the`gh-pages` branch with the docs...

**Comment by jagoosw** [comment]
I just used this script https://gist.github.com/mcxiaoke/b4bdad5727c9400bbf7d101f27297e86 to find the largest files and the biggest are generated output files (which I thougt were getting deleted at the end of the docs script but they're not) in the docs, and some data files from a long time ago that have since been deleted.

I'll update the docs script to delete outputs, but how can I get rid of files in the history?

**Comment by navidcy** [comment]
I've done things like that with https://rtyley.github.io/bfg-repo-cleaner/ before. But everyone that has a clone of the repo needs to ensure they delete and make a new clone, which is annoying.

Are all these files _only_ in the `gh-branch`? If so there might be an easier alternative.

**Comment by navidcy** [comment]
I realized that the `.jld2`/`.nc` filed from the literated examples also don't get deleted in Oceananigans either!

I think 

https://github.com/OceanBioME/OceanBioME.jl/blob/3378d6df3b2d463a4b4a5d8a3ec0c073525fbde5/docs/make.jl#L127

needs to be changed to

```Julia
for file in vcat(glob("docs/**/*.jld2"), glob("docs/**/*.nc")) 
```

**Comment by jagoosw** [comment]
There are two in the history for the main branch which total about 100MB. I don't think anyone else is activly working on the repo so everyone recloning might not be too hard?

@johnryantaylor @syou83syou83 @iuryt would you mind if we did this?

**Comment by iuryt** [comment]
No problem for me at all!

**Comment by johnryantaylor** [comment]
Sounds fine to me too. On May 18, 2023, at 7:10 PM, iury simoes-sousa ***@***.***> wrote:﻿
No problem for me at all!

**Comment by navidcy** [comment]
@jagoosw if you give me admin rights I can cleanup the `gh-pages` branch from these large files.

**Comment by johnryantaylor** [comment]
@navidcy, thanks for all of your help with this and the other issues!  I have you and @glwagner  admin rights for OceanBioME

**Comment by jagoosw** [comment]
Thank you!

**Comment by jagoosw** [comment]
We need everyone to re-clone the repo right?

**Comment by navidcy** [comment]
Nope for that.

**Comment by navidcy** [comment]
But if we want to clear up some output files from main then we’d have to reclone.
