### ISSUE TITLE
`SLatissima` parameters do not show

### ISSUE THREAD

**Issue by navidcy** [OceanBioME/OceanBioME.jl#98]
This snipped

https://github.com/OceanBioME/OceanBioME.jl/blob/1c5598ec482c97f92008250d6071c3d491a3e5c1/docs/src/appendix/params/SLatissima.md#L4-L5

doesn't seem to be doing anything.

**Comment by jagoosw** [comment]
Oh yeah that doesn't work anymore. I'd quite like to document the default parameters somehow but haven't worked out how todo it yet.
